### ISSUE TITLE
Submit extension to addons.mozilla.org

### ISSUE THREAD

**Issue by valenting** [dizzu/denecrezut.faction.ro#1]
This is a really fantastic extension, but having it be Chrome only really reduces its benefit.
Making this available to Firefox users should be really easy. 

https://developer.mozilla.org/en-US/Add-ons/WebExtensions
https://hacks.mozilla.org/2015/10/porting-chrome-extensions-to-firefox-with-webextensions/

@dizzu If you don't have the time/interest in this project, I could volunteer some time and do it myself.

**Comment by dizzu** [comment]
Hello,
I've tried porting it to Firefox but did not give it too much attention.
Seems pretty easy, but haven't got the time.
I'm adding some really cool features these days, and after that if you have the time, a port to Firefox would be awesome.

**Comment by valenting** [comment]
So, I noticed that you've already uploaded the extension to AMO:
https://addons.mozilla.org/en-US/firefox/addon/de-necrezut/

I've created a patch that makes it work in Firefox. Let me know if you can apply it yourself, or if I should submit a pull request.
https://gist.github.com/valenting/f64b255487817440dc126582c4689e88

Please note that the added CSS seems to mess up facebook's alignment: http://imgur.com/a/mDi9X

**Comment by dizzu** [comment]
That's great.
I'll try to apply the patch and resubmit it to the Mozilla Store.
Thanks!

**Comment by dizzu** [comment]
I've applied the patch and all is working as it should in Firefox. Thank you!
